#!/usr/bin/env bash
#
# Mount host home directory in development box
# Steps to install:
# 1. Append the main host address in /etc/hosts:
#    $ echo '192.168.122.1   mainhost' >> /etc/hosts
# 2. Add this file as a executable command: /usr/bin/mount-mainhost
# 3. Append .bashrc file with this line: '/usr/bin/mount-mainhost'
#

mount_point="${HOME}/mainhost"

if mount | grep "${mount_point}" >/dev/null; then
    echo "Main host home directory is already mounted!"
else
    if [ "$(whoami)" = 'root' ]; then
        # Prevents remounting of directory while using sudo
        exit 0
    fi
    mkdir -p "${mount_point}"
    nohup sshfs rohit@mainhost: "${mount_point}" \
        -o reconnect,idmap=user,dev,suid > /dev/null
    if mount | grep "${mount_point}" >/dev/null; then
        echo "Main host home directory successfully mounted on ${mount_point}"
    else
        echo "Main host mount failed. Please check connection."
        exit 1
    fi
fi
